# Generated by Django 5.0.6 on 2024-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
